<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" hostname="d67841e374a7" name="pytest" skipped="0" tests="37" time="1.464" timestamp="2021-10-22T20:48:58.889156"><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="99" name="test_empty_get" time="0.007"></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="113" name="test_get_next" time="0.006"><system-out>empty_get: {&apos;records&apos;: [&apos;data1&apos;, &apos;data2&apos;], &apos;_links&apos;: {&apos;self&apos;: &apos;me&apos;}}
</system-out></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="142" name="test_negative_get_next_no_href" time="0.007"><system-out>error: Expecting href key in {}
</system-out></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="128" name="test_negative_get_next_no__links" time="0.008"><system-out>error: Expecting _links key in {}
</system-out></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="164" name="test_has_feature_success_default_1" time="0.006"></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="156" name="test_has_feature_success_default_0" time="0.009"></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="181" name="test_has_feature_success_user_false" time="0.008"><system-out>{&apos;username&apos;: &apos;test_user&apos;, &apos;feature_flags&apos;: {&apos;user_deprecation_warning&apos;: False}, &apos;password&apos;: &apos;test_pass!&apos;, &apos;hostname&apos;: &apos;test&apos;}
</system-out></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="172" name="test_has_feature_success_user_true" time="0.005"></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="203" name="test_empty_get_sent" time="0.006"></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="191" name="test_has_feature_invalid_key" time="0.006"></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="214" name="test_empty_get_sent_bad_json" time="0.008"><system-out>errors: [&apos;Other error: Expecting json, got: anything&apos;]
debug: [(&apos;sending&apos;, &quot;{&apos;headers&apos;: None, &apos;json&apos;: None, &apos;params&apos;: None, &apos;timeout&apos;: 60, &apos;url&apos;: &apos;https://test/api/api&apos;, &apos;verify&apos;: True, &apos;method&apos;: &apos;GET&apos;}&quot;), (200, &apos;Other error: Expecting json, got: anything&apos;), (200, &apos;anything&apos;)]
</system-out></testcase><testcase classname="modules.test_na_um_list_aggregates.TestMyModule" file="modules/test_na_um_list_aggregates.py" line="130" name="test_get_next" time="0.007"></testcase><testcase classname="module_utils.test_netapp" file="module_utils/test_netapp.py" line="226" name="test_empty_get_sent_bad_but_empty_json" time="0.007"><system-out>errors: []
debug: [(&apos;sending&apos;, &quot;{&apos;headers&apos;: None, &apos;json&apos;: None, &apos;params&apos;: None, &apos;timeout&apos;: 60, &apos;url&apos;: &apos;https://test/api/api&apos;, &apos;verify&apos;: True, &apos;method&apos;: &apos;GET&apos;}&quot;), (200, &apos;&apos;)]
</system-out></testcase><testcase classname="modules.test_na_um_list_aggregates.TestMyModule" file="modules/test_na_um_list_aggregates.py" line="103" name="test_module_fail_when_required_args_missing" time="0.006"><system-out>Info: missing required arguments: hostname, password, username
</system-out></testcase><testcase classname="modules.test_na_um_list_aggregates.TestMyModule" file="modules/test_na_um_list_aggregates.py" line="142" name="test_negative_get_next" time="0.007"><system-out>{&apos;msg&apos;: &quot;Error: unexpected response from datacenter/storage/aggregates?order_by=performance_capacity.used: {&apos;records&apos;: [&apos;data1&apos;, &apos;data2&apos;], &apos;_links&apos;: {&apos;self&apos;: &apos;me&apos;}} - expecting key: &apos;total_records&apos;&quot;, &apos;failed&apos;: True}
</system-out></testcase><testcase classname="modules.test_na_um_list_aggregates.TestMyModule" file="modules/test_na_um_list_aggregates.py" line="122" name="test_ensure_get_called_existing" time="0.008"></testcase><testcase classname="modules.test_na_um_list_clusters.TestMyModule" file="modules/test_na_um_list_clusters.py" line="122" name="test_ensure_get_called_existing" time="0.007"></testcase><testcase classname="modules.test_na_um_list_aggregates.TestMyModule" file="modules/test_na_um_list_aggregates.py" line="110" name="test_ensure_list_aggregates_get_called" time="0.007"></testcase><testcase classname="modules.test_na_um_list_clusters.TestMyModule" file="modules/test_na_um_list_clusters.py" line="110" name="test_ensure_list_cluster_get_called" time="0.008"></testcase><testcase classname="modules.test_na_um_list_clusters.TestMyModule" file="modules/test_na_um_list_clusters.py" line="142" name="test_negative_get_next" time="0.008"><system-out>{&apos;msg&apos;: &quot;Error: unexpected response from datacenter/cluster/clusters: {&apos;records&apos;: [&apos;data1&apos;, &apos;data2&apos;], &apos;_links&apos;: {&apos;self&apos;: &apos;me&apos;}} - expecting key: &apos;total_records&apos;&quot;, &apos;failed&apos;: True}
</system-out></testcase><testcase classname="modules.test_na_um_list_clusters.TestMyModule" file="modules/test_na_um_list_clusters.py" line="130" name="test_get_next" time="0.007"></testcase><testcase classname="modules.test_na_um_list_nodes.TestMyModule" file="modules/test_na_um_list_nodes.py" line="121" name="test_ensure_get_called_existing" time="0.007"></testcase><testcase classname="modules.test_na_um_list_nodes.TestMyModule" file="modules/test_na_um_list_nodes.py" line="110" name="test_ensure_list_nodes_get_called" time="0.007"></testcase><testcase classname="modules.test_na_um_list_clusters.TestMyModule" file="modules/test_na_um_list_clusters.py" line="103" name="test_module_fail_when_required_args_missing" time="0.006"><system-out>Info: missing required arguments: hostname, password, username
</system-out></testcase><testcase classname="modules.test_na_um_list_nodes.TestMyModule" file="modules/test_na_um_list_nodes.py" line="129" name="test_get_next" time="0.007"></testcase><testcase classname="modules.test_na_um_list_nodes.TestMyModule" file="modules/test_na_um_list_nodes.py" line="141" name="test_negative_get_next" time="0.009"><system-out>{&apos;msg&apos;: &quot;Error: unexpected response from datacenter/cluster/nodes?order_by=performance_capacity.used: {&apos;records&apos;: [&apos;data1&apos;, &apos;data2&apos;], &apos;_links&apos;: {&apos;self&apos;: &apos;me&apos;}} - expecting key: &apos;total_records&apos;&quot;, &apos;failed&apos;: True}
</system-out></testcase><testcase classname="modules.test_na_um_list_nodes.TestMyModule" file="modules/test_na_um_list_nodes.py" line="103" name="test_module_fail_when_required_args_missing" time="0.006"><system-out>Info: missing required arguments: hostname, password, username
</system-out></testcase><testcase classname="modules.test_na_um_list_svms.TestMyModule" file="modules/test_na_um_list_svms.py" line="121" name="test_ensure_get_called_existing" time="0.007"></testcase><testcase classname="modules.test_na_um_list_svms.TestMyModule" file="modules/test_na_um_list_svms.py" line="110" name="test_ensure_list_svms_get_called" time="0.010"></testcase><testcase classname="modules.test_na_um_list_svms.TestMyModule" file="modules/test_na_um_list_svms.py" line="129" name="test_get_next" time="0.008"></testcase><testcase classname="modules.test_na_um_list_svms.TestMyModule" file="modules/test_na_um_list_svms.py" line="103" name="test_module_fail_when_required_args_missing" time="0.008"><system-out>Info: missing required arguments: hostname, password, username
</system-out></testcase><testcase classname="modules.test_na_um_list_svms.TestMyModule" file="modules/test_na_um_list_svms.py" line="141" name="test_negative_get_next" time="0.007"><system-out>{&apos;msg&apos;: &quot;Error: unexpected response from datacenter/svm/svms: {&apos;records&apos;: [&apos;data1&apos;, &apos;data2&apos;], &apos;_links&apos;: {&apos;self&apos;: &apos;me&apos;}} - expecting key: &apos;total_records&apos;&quot;, &apos;failed&apos;: True}
</system-out></testcase><testcase classname="modules.test_na_um_list_volumes.TestMyModule" file="modules/test_na_um_list_volumes.py" line="121" name="test_ensure_get_called_existing" time="0.007"></testcase><testcase classname="modules.test_na_um_list_volumes.TestMyModule" file="modules/test_na_um_list_volumes.py" line="110" name="test_ensure_list_volumes_get_called" time="0.008"></testcase><testcase classname="modules.test_na_um_list_volumes.TestMyModule" file="modules/test_na_um_list_volumes.py" line="103" name="test_module_fail_when_required_args_missing" time="0.006"><system-out>Info: missing required arguments: hostname, password, username
</system-out></testcase><testcase classname="modules.test_na_um_list_volumes.TestMyModule" file="modules/test_na_um_list_volumes.py" line="129" name="test_get_next" time="0.007"></testcase><testcase classname="modules.test_na_um_list_volumes.TestMyModule" file="modules/test_na_um_list_volumes.py" line="141" name="test_negative_get_next" time="0.008"><system-out>{&apos;msg&apos;: &quot;Error: unexpected response from datacenter/storage/volumes: {&apos;records&apos;: [&apos;data1&apos;, &apos;data2&apos;], &apos;_links&apos;: {&apos;self&apos;: &apos;me&apos;}} - expecting key: &apos;total_records&apos;&quot;, &apos;failed&apos;: True}
</system-out></testcase></testsuite></testsuites>